SWP391.OnlineShop.Core/Cores/IRepositories/IFeedBackRepository.cs
SWP391.OnlineShop.Core/Cores/IRepositories/IPostRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/FeedBackRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/PostRepository.cs

OSP. create methods in Feedback and Post Repository

OSP. create methods in Feedback and Post Repository

---

SWP391.OnlineShop.Core/Contexts/OnlineShopDbInitializer.cs
SWP391.OnlineShop.Core/Cores/IRepositories/IOrderRepository.cs
SWP391.OnlineShop.Core/Cores/IRepositories/IVoucherRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/OrderRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/VoucherRepository.cs
SWP391.OnlineShop.Core/Migrations/20230920165731_Add_Column_OrderStatus_To_Table_Orders.Designer.cs
SWP391.OnlineShop.Core/Migrations/20230920165731_Add_Column_OrderStatus_To_Table_Orders.cs
SWP391.OnlineShop.Core/Models/Entities/Order.cs
SWP391.OnlineShop.Core/Models/Enums/AllStatus.cs
SWP391.OnlineShop.Core/SWP391.OnlineShop.Core.csproj
SWP391.OnlineShop.Portal/Program.cs
SWP391.OnlineShop.Portal/SWP391.OnlineShop.Portal.csproj

OPS: Seed Data, Add OrderStatus and Update Order,Voucher Repo

OPS: Seed Data, Add OrderStatus and Update Order,Voucher Repo

---

SWP391.OnlineShop.Core/Cores/IRepositories/IProductRepository.cs
SWP391.OnlineShop.Portal/Controllers/HomeController.cs
SWP391.OnlineShop.Portal/Views/Home/Index.cshtml
SWP391.OnlineShop.Service/Configs/AutoMapper/AutoMapperConfigs.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/IPostService.cs
SWP391.OnlineShop.ServiceInterface/Services/PostService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/PostModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Products/PostViewModel.cs

OSP. Add Service Logic for Post

OSP. Add Service Logic for Post

---

SWP391.OnlineShop.Portal/Controllers/HomeController.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/IPostService.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/IProductService.cs
SWP391.OnlineShop.ServiceInterface/Services/PostService.cs
SWP391.OnlineShop.ServiceInterface/Services/ProductService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/PostModels.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/ProductModels.cs

OSP: Update Service Product, Post

OSP: Update Service Product, Post

---

SWP391.OnlineShop.Core/Cores/IRepositories/IPostRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/PostRepository.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/IPostService.cs
SWP391.OnlineShop.ServiceInterface/Services/PostService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/PostModels.cs

OSP: Add Post Service Logic

---

SWP391.OnlineShop.Core/Cores/IRepositories/IOrderRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/OrderRepository.cs
SWP391.OnlineShop.Portal/Controllers/CartController.cs
SWP391.OnlineShop.Portal/Views/Cart/Index.cshtml
SWP391.OnlineShop.ServiceInterface/Interfaces/IOrderService.cs
SWP391.OnlineShop.ServiceInterface/Services/OrderService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/OrderModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Cart/OrderDetailViewModel.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Cart/OrderViewModel.cs

OSP: Update Cart Function

---

SWP391.OnlineShop.Portal/Controllers/MarketingController.cs
SWP391.OnlineShop.Portal/Views/Marketing/AddPost.cshtml
SWP391.OnlineShop.Portal/Views/Marketing/EditPost.cshtml
SWP391.OnlineShop.Portal/Views/Marketing/ManagePost.cshtml
SWP391.OnlineShop.Portal/Views/Marketing/ViewPost.cshtml
SWP391.OnlineShop.Portal/Views/Marketing/ViewProduct.cshtml
SWP391.OnlineShop.ServiceModel/ViewModels/Products/PostViewModel.cs

OSP: Update CRUD Product for Marketing role

OSP: Update CRUD Product for Marketing role

---

SWP391.OnlineShop.Core/Cores/Repositories/ProductRepository.cs
SWP391.OnlineShop.Portal/Controllers/HomeController.cs
SWP391.OnlineShop.Portal/Controllers/ProductController.cs
SWP391.OnlineShop.Portal/Views/Home/Index.cshtml
SWP391.OnlineShop.Portal/Views/Product/Details.cshtml
SWP391.OnlineShop.Portal/Views/Product/Index.cshtml
SWP391.OnlineShop.ServiceInterface/Interfaces/IProductService.cs
SWP391.OnlineShop.ServiceInterface/Services/CategoryService.cs
SWP391.OnlineShop.ServiceInterface/Services/ProductService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/ProductModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Category/CategoryViewModel.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Products/HomeViewModel.cs

OSP: Update Home, Product Detail page, Add new comment

OSP: Update Home, Product Detail page, Add new comment

---

SWP391.OnlineShop.Core/Migrations/20231014054838_Add_OrderNote_To_OrderTable.Designer.cs
SWP391.OnlineShop.Core/Migrations/20231014054838_Add_OrderNote_To_OrderTable.cs
SWP391.OnlineShop.Core/Models/Entities/Order.cs
SWP391.OnlineShop.Core/Models/Enums/AllStatus.cs
SWP391.OnlineShop.Portal/Controllers/CartController.cs
SWP391.OnlineShop.Portal/Views/Cart/Checkout.cshtml
SWP391.OnlineShop.Portal/Views/Cart/Confirmation.cshtml
SWP391.OnlineShop.Portal/Views/Cart/Index.cshtml
SWP391.OnlineShop.Portal/Views/Product/Details.cshtml
SWP391.OnlineShop.Service/Configs/AutoMapper/AutoMapperConfigs.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/IEmailService.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/IOrderService.cs
SWP391.OnlineShop.ServiceInterface/Services/EmailService.cs
SWP391.OnlineShop.ServiceInterface/Services/OrderService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/EmailModel.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/OrderModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Cart/OrderViewModel.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Emails/EmailViewModel.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Products/ProductViewModel.cs

OSP: Write Add To Cart function

OSP: Write Add To Cart function

---

SWP391.OnlineShop.Portal/Controllers/MarketingController.cs
SWP391.OnlineShop.Portal/Views/Marketing/AddProduct.cshtml
SWP391.OnlineShop.Portal/Views/Marketing/EditProduct.cshtml
SWP391.OnlineShop.Portal/Views/Marketing/Index.cshtml
SWP391.OnlineShop.ServiceInterface/Services/PostService.cs
SWP391.OnlineShop.ServiceInterface/Services/ProductService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/ProductModels.cs

OSP: Update CRUD Product

---

SWP391.OnlineShop.ServiceModel/ServiceModels/ProductModels.cs

OSP: Update merge conflict

---

SWP391.OnlineShop.ServiceInterface/Services/ProductService.cs

OSP: Resolve conflict

---

SWP391.OnlineShop.Core/Migrations/20231025163428_Add_Column_VoucherType_And_Column_Value_To_Voucher_Table.Designer.cs
SWP391.OnlineShop.Core/Migrations/20231025163428_Add_Column_VoucherType_And_Column_Value_To_Voucher_Table.cs
SWP391.OnlineShop.Core/Models/Entities/Voucher.cs
SWP391.OnlineShop.Core/Models/Enums/AllStatus.cs
SWP391.OnlineShop.Service/Configs/AutoMapper/AutoMapperConfigs.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/IVoucherService.cs
SWP391.OnlineShop.ServiceInterface/Services/VoucherService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/VoucherModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Vouchers/VoucherViewModels.cs

OSP: Update CRUD Voucher

---

SWP391.OnlineShop.Core/Cores/IRepositories/IPostRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/PostRepository.cs
SWP391.OnlineShop.Portal/Controllers/PostController.cs
SWP391.OnlineShop.Portal/Views/Post/Details.cshtml
SWP391.OnlineShop.Portal/Views/Post/Index.cshtml
SWP391.OnlineShop.Service/Configs/AutoMapper/AutoMapperConfigs.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/IPostService.cs
SWP391.OnlineShop.ServiceInterface/Services/PostService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/PostModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Products/PostViewModel.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Tags/TagViewModel.cs

OSP: Update Post List and Post Detail

OSP: Update Post List and Post Detail

---

SWP391.OnlineShop.Core/Migrations/20231030163345_Update_Relationship_Voucher_ProductVoucher_Table.Designer.cs
SWP391.OnlineShop.Core/Migrations/20231030163345_Update_Relationship_Voucher_ProductVoucher_Table.cs
SWP391.OnlineShop.Core/Models/EntityConfigs/ProductVoucherConfigs.cs
SWP391.OnlineShop.Portal/Areas/Managements/Controllers/CategoryController.cs
SWP391.OnlineShop.Portal/Areas/Managements/Controllers/VoucherController.cs
SWP391.OnlineShop.Portal/Areas/Managements/Views/Category/Add.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Category/Index.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Category/Update.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Shared/AdminPartial/_AdminSidebarPartial.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Voucher/Add.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Voucher/Index.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Voucher/Update.cshtml
SWP391.OnlineShop.ServiceInterface/Interfaces/IProductService.cs
SWP391.OnlineShop.ServiceInterface/Services/ProductService.cs
SWP391.OnlineShop.ServiceInterface/Services/VoucherService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/ProductModels.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/VoucherModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Categories/CategoryViewModel.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Vouchers/VoucherViewModels.cs

OSP: Update Voucher Management + Update UI for Category Management

OSP: Update Voucher Management + Update UI for Category Management

---

SWP391.OnlineShop.Portal/Views/Marketing/AddPost.cshtml
SWP391.OnlineShop.Portal/Views/Marketing/AddProduct.cshtml
SWP391.OnlineShop.Portal/Views/Marketing/EditPost.cshtml
SWP391.OnlineShop.Portal/Views/Marketing/EditProduct.cshtml

OSP: Remove button Reset

---

SWP391.OnlineShop.Core/Cores/IRepositories/IPostRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/PostRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/ProductRepository.cs
SWP391.OnlineShop.Portal/Controllers/PostController.cs
SWP391.OnlineShop.Portal/Controllers/ProductController.cs
SWP391.OnlineShop.Portal/Views/Post/Index.cshtml
SWP391.OnlineShop.Portal/Views/Product/Details.cshtml
SWP391.OnlineShop.ServiceInterface/Services/ProductService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/ProductModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Feedback/FeedbackViewModels.cs

OSP: Update Comment, Post Paging, Search

OSP: Update Comment, Post Paging, Search

---

SWP391.OnlineShop.Portal/Views/Post/Details.cshtml
SWP391.OnlineShop.Portal/Views/Product/Details.cshtml
SWP391.OnlineShop.Portal/Views/Product/Index.cshtml

OSP: Fix display price

---

SWP391.OnlineShop.Core/Cores/IRepositories/IProductRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/ProductRepository.cs
SWP391.OnlineShop.Portal/Views/Home/Index.cshtml
SWP391.OnlineShop.Portal/Views/Product/Details.cshtml
SWP391.OnlineShop.Portal/Views/Product/Index.cshtml
SWP391.OnlineShop.ServiceInterface/Services/ProductService.cs

OSP: Update Deal of week

---

SWP391.OnlineShop.Portal/Views/Cart/Index.cshtml

OSP: Update UI

---

SWP391.OnlineShop.Core/Cores/Repositories/PostRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/ProductRepository.cs
SWP391.OnlineShop.Portal/Areas/Managements/Controllers/MarketingController.cs
SWP391.OnlineShop.Portal/Areas/Managements/Views/Marketing/ManageTag.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Shared/AdminPartial/_AdminSidebarPartial.cshtml
SWP391.OnlineShop.Portal/Controllers/HomeController.cs
SWP391.OnlineShop.Portal/Views/Home/Index.cshtml
SWP391.OnlineShop.Portal/Views/Product/Details.cshtml
SWP391.OnlineShop.Portal/Views/Product/Index.cshtml
SWP391.OnlineShop.ServiceInterface/Services/CategoryService.cs
SWP391.OnlineShop.ServiceInterface/Services/PostService.cs
SWP391.OnlineShop.ServiceInterface/Services/ProductService.cs
SWP391.OnlineShop.ServiceInterface/Services/SliderService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/PostModels.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/ProductModels.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/SliderModel.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/TagModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Products/HomeViewModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Tags/TagViewModel.cs

OSP: Fix bugs products

---

SWP391.OnlineShop.Core/Cores/Repositories/ProductRepository.cs
SWP391.OnlineShop.Portal/Controllers/ProductController.cs
SWP391.OnlineShop.Portal/Views/Product/Details.cshtml
SWP391.OnlineShop.Service/Configs/AutoMapper/AutoMapperConfigs.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/IProductService.cs
SWP391.OnlineShop.ServiceInterface/Services/ProductService.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Products/ProductSizeViewModel.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Products/ProductViewModel.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Products/SizeViewModel.cs

OSP: Load Size in Product Detail

OSP: Load Size in Product Detail

---

SWP391.OnlineShop.Core/Cores/IRepositories/ISizeRepository.cs
SWP391.OnlineShop.Core/Cores/Repositories/SizeRepository.cs
SWP391.OnlineShop.Core/Cores/UnitOfWork/IUnitOfWork.cs
SWP391.OnlineShop.Core/Cores/UnitOfWork/UnitOfWork.cs
SWP391.OnlineShop.Core/SWP391.OnlineShop.Core.csproj
SWP391.OnlineShop.Portal/Areas/Managements/Controllers/MarketingController.cs
SWP391.OnlineShop.Portal/Areas/Managements/Views/Marketing/AddProduct.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Marketing/AddSize.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Marketing/EditProduct.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Marketing/EditSize.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Marketing/ManageSize.cshtml
SWP391.OnlineShop.Portal/Areas/Managements/Views/Marketing/ViewProduct.cshtml
SWP391.OnlineShop.Portal/Controllers/HomeController.cs
SWP391.OnlineShop.Portal/Controllers/ProductController.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/IProductService.cs
SWP391.OnlineShop.ServiceInterface/Interfaces/ISizeService.cs
SWP391.OnlineShop.ServiceInterface/Services/ProductService.cs
SWP391.OnlineShop.ServiceInterface/Services/SizeService.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/ProductModels.cs
SWP391.OnlineShop.ServiceModel/ServiceModels/SizeModels.cs
SWP391.OnlineShop.ServiceModel/ViewModels/Products/SizeViewModel.cs

OSP: Add Manage Size, Add Product quantity

OSP: Add Manage Size, Add Product quantity

---

SWP391.OnlineShop.Portal/Views/Cart/Checkout.cshtml

OSP: Update Checkout Screen

---

SWP391.OnlineShop.Portal/Areas/Managements/Views/Marketing/AddPost.cshtml
SWP391.OnlineShop.Portal/Controllers/HomeController.cs

OSP: Fix merge issue
